
services:
  pgmaster:
    image: postgres:15-alpine
    container_name: pgmaster
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: social_network
    volumes:
      - ./volumes/pgmaster:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pgnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_network"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgmaster-exporter:
    image: wrouesnel/postgres_exporter
    container_name: pgmaster-exporter
    networks:
      - pgnet
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@pgmaster:5432/social_network?sslmode=disable"
    depends_on:
      - pgmaster

  pgslave:
    image: postgres:15-alpine
    container_name: pgslave
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: social_network
    volumes:
      - ./volumes/pgslave:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - pgnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgslave-exporter:
    image: wrouesnel/postgres_exporter
    container_name: pgslave-exporter
    networks:
      - pgnet
    ports:
      - "9188:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@pgslave:5432/social_network?sslmode=disable"
    depends_on:
      - pgslave

  pgasyncslave:
    image: postgres:15-alpine
    container_name: pgasyncslave
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: social_network
    volumes:
      - ./volumes/pgasyncslave:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - pgnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgasyncslave-exporter:
    image: wrouesnel/postgres_exporter
    container_name: pgasyncslave-exporter
    networks:
      - pgnet
    ports:
      - "9189:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@pgasyncslave:5432/social_network?sslmode=disable"
    depends_on:
      - pgasyncslave

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
#      SPRING_PROFILES_ACTIVE: master-only
      SPRING_PROFILES_ACTIVE: replication
      SPRING_DATASOURCE_MASTER_JDBC_URL: jdbc:postgresql://pgmaster:5432/social_network
      SPRING_DATASOURCE_MASTER_USERNAME: postgres
      SPRING_DATASOURCE_MASTER_PASSWORD: postgres
      SPRING_DATASOURCE_SLAVE_JDBC_URL: jdbc:postgresql://pgslave:5432/social_network
      SPRING_DATASOURCE_SLAVE_USERNAME: postgres
      SPRING_DATASOURCE_SLAVE_PASSWORD: postgres
      SPRING_DATASOURCE_ASYNCSLAVE_JDBC_URL: jdbc:postgresql://pgasyncslave:5432/social_network
      SPRING_DATASOURCE_ASYNCSLAVE_USERNAME: postgres
      SPRING_DATASOURCE_ASYNCSLAVE_PASSWORD: postgres
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_DATASOURCE: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE: TRACE
    depends_on:
      pgmaster:
        condition: service_healthy
    networks:
      - pgnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - pgnet
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - pgnet
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

networks:
  pgnet:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: