global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'postgres'
    static_configs:
      - targets:
        - 'pgmaster-exporter:9187'
        - 'pgslave-exporter:9187'
        - 'pgasyncslave-exporter:9187'
        labels:
          group: 'postgresql-cluster'

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8080' ]

  - job_name: 'application'
    static_configs:
      - targets: [ 'localhost:8080' ]