spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/network
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: mySuperSecretKeyThatIsAtLeast32CharactersLong!
    expiration: 86400000